version: '3.7'

services:
  mongodb:
    image: mongo:4.0.3-xenial
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: [ "mongod", "--smallfiles" ]
    logging:
      driver: "none"

  web:
    build: .
    command: npm test
    volumes:
      - /usr/src/app
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
    links:
      - mongodb
